export {default as Navbar} from './Navbar'
export {default as Footer} from './Footer'
export {default as Home} from './Home'
export {default as Cryptocurrencies} from './Cryptocurrencies'
export {default as News} from './News'
export {default as CryptoDetails} from './CryptoDetails'
export {default as Loader} from './Loader'